/** Modèles d'inspection alignés sur les pratiques courantes au Québec */

import { AIBQ_SECTIONS, BNQ_SECTIONS } from './templates-aibq-bnq-full.js';
import { batimentGrenierSection } from './field-walk-sections.js';
import { defaultVisit } from './visit.js';
import { INSPECTOR_NAME } from './storage.js';

export const TEMPLATE_META = {
  'etat-lieux': {
    id: 'etat-lieux',
    label: 'État des lieux',
    norme: 'Régie du logement / usage courant',
    icon: '🏠',
    description: 'Entrée/sortie de bail, inventaire pièce par pièce, preuves photographiques.',
    group: 'autre',
  },
  batiment: {
    id: 'batiment',
    label: 'Bâtiment résidentiel',
    norme: 'Code du bâtiment du Québec (CBQ)',
    icon: '🏗️',
    description: 'Structure, sécurité incendie, sorties, garde-corps, détecteurs.',
    group: 'autre',
  },
  cnesst: {
    id: 'cnesst',
    label: 'SST — chantier / atelier',
    norme: 'Loi sur la SST, CNESST',
    icon: '⛑️',
    description: 'Prévention, signalisation, EPI, échafaudages, électricité temporaire.',
    group: 'autre',
  },
  mapaq: {
    id: 'mapaq',
    label: 'Alimentaire',
    norme: 'Règlement MAPAQ / Loi sur les aliments',
    icon: '🍽️',
    description: 'Chaîne du froid, hygiène, contamination croisée, traçabilité.',
    group: 'autre',
  },
  incendie: {
    id: 'incendie',
    label: 'Sécurité incendie',
    norme: 'CNPI / municipalité',
    icon: '🔥',
    description: 'Issues, extincteurs, alarmes, plans d\'évacuation, compartimentage.',
    group: 'autre',
  },
  'aibq-preachat': {
    id: 'aibq-preachat',
    label: 'Inspection préachat AIBQ',
    norme: 'Norme de pratique AIBQ (préachat résidentiel)',
    icon: '🏡',
    description: 'Norme complète : chapitres I à V, 11 systèmes, rapport, annexe I (arts 1-60).',
    group: 'aibq-bnq',
    reference: 'aibq.qc.ca — Norme de pratique inspection préachat',
  },
  'bnq-3009': {
    id: 'bnq-3009',
    label: 'Transaction immobilière BNQ',
    norme: 'BNQ 3009-500/2022 R1 — inspection résidentielle',
    icon: '📐',
    description: 'Norme complète : ch. 2 à 12, processus, éthique, dossier et art. 12.1 à 12.8.',
    group: 'aibq-bnq',
    reference: 'bnq.qc.ca — Bâtiment d\'habitation, transaction immobilière',
  },
  custom: {
    id: 'custom',
    label: 'Liste personnalisée',
    norme: 'À définir',
    icon: '✏️',
    description: 'Créez vos propres sections et points de contrôle.',
    group: 'autre',
  },
};

/** Ordre d'affichage des groupes de modèles */
export const TEMPLATE_GROUPS = {
  'aibq-bnq': { label: 'AIBQ & BNQ (inspection immobilière)', order: 0 },
  autre: { label: 'Autres inspections', order: 1 },
};

export const STATUS_OPTIONS = [
  { value: 'conforme', label: 'Conforme', short: 'C' },
  { value: 'non-conforme', label: 'Non conforme', short: 'NC' },
  { value: 'a-corriger', label: 'À corriger', short: 'AC' },
  { value: 'na', label: 'S.O. / N/A', short: 'N/A' },
];

export const PRIORITY_OPTIONS = [
  { value: 'critique', label: 'Critique' },
  { value: 'majeur', label: 'Majeur' },
  { value: 'mineur', label: 'Mineur' },
];

export const INSPECTION_STATUS = {
  brouillon: { label: 'Brouillon', class: 'badge--draft' },
  'en-cours': { label: 'En cours', class: 'badge--progress' },
  terminee: { label: 'Terminée', class: 'badge--done' },
  archivee: { label: 'Archivée', class: 'badge--archived' },
};

function section(id, title, items) {
  return {
    id,
    title,
    items: items.map((label, i) => ({
      id: `${id}-${i + 1}`,
      label,
      status: null,
      priority: 'mineur',
      note: '',
      selectedPresets: [],
      inspectorComment: '',
      photos: [],
    })),
  };
}

export const TEMPLATES = {
  'etat-lieux': {
    sections: [
      section('edl-general', 'Informations générales', [
        'Type de constat : entrée ou sortie',
        'Nombre de pièces inspectées',
        'Relevé des compteurs (électricité, gaz, eau)',
        'Clés et télécommandes remises (nombre et type)',
        'Boîte aux lettres et interphone',
        'Signalisation et numéro de porte',
      ]),
      section('edl-entree', 'Entrée et corridors', [
        'Porte d\'entrée : état, serrure, clé, seuil',
        'Murs : état de la peinture, trous, fissures, taches',
        'Plafond : fissures, taches d\'eau, peinture écaillée',
        'Plancher : revêtement, usure, dommages',
        'Prises électriques et interrupteurs fonctionnels',
        'Éclairage : plafonnier, appliques',
        'Détecteur de fumée présent et fonctionnel',
      ]),
      section('edl-salon', 'Salon / Séjour', [
        'Murs : peinture, papier peint, fissures, trous',
        'Plafond : état général, traces d\'humidité',
        'Plancher : parquet, tapis, carrelage — état',
        'Fenêtres : vitrage, mécanisme, étanchéité, moustiquaire',
        'Stores, rideaux ou toiles (si inclus)',
        'Prises électriques, interrupteurs, câble/téléphone',
        'Chauffage : plinthes, radiateur, calorifère — état',
        'Portes intérieures : état, poignée, fermeture',
      ]),
      section('edl-cuisine', 'Cuisine', [
        'Comptoirs et dosseret : fissures, taches, brûlures',
        'Armoires et tiroirs : état, charnières, poignées',
        'Évier et robinetterie : état, débit, drainage',
        'Cuisinière / four : état et fonctionnement',
        'Réfrigérateur : état, joints, fonctionnement',
        'Lave-vaisselle (si inclus) : état et fonctionnement',
        'Hotte de ventilation : fonctionnement, filtre',
        'Plancher : revêtement, taches, usure',
        'Murs et plafond : état de la peinture',
        'Prises GFCI et interrupteurs',
        'Fenêtre : vitrage, mécanisme',
      ]),
      section('edl-sdb', 'Salle de bain principale', [
        'Toilette : état, chasse d\'eau, siège, base',
        'Lavabo et robinetterie : état, débit, drainage',
        'Baignoire ou douche : état, joints, robinets',
        'Carrelage mural et plancher : joints, fissures',
        'Ventilateur d\'extraction : fonctionnement',
        'Miroir et armoire à pharmacie',
        'Porte-serviette, crochets, accessoires',
        'Traces d\'humidité, moisissure, dégât d\'eau',
        'Plancher : état du revêtement',
      ]),
      section('edl-sdb2', 'Salle de bain secondaire (si applicable)', [
        'Toilette, lavabo, douche/bain : état complet',
        'Carrelage, joints et étanchéité',
        'Ventilation et traces d\'humidité',
        'Accessoires et miroir',
      ]),
      section('edl-chambre1', 'Chambre principale', [
        'Murs : peinture, trous, fissures',
        'Plafond : état, traces d\'eau',
        'Plancher : état du revêtement',
        'Fenêtres : vitrage, mécanisme, stores',
        'Garde-robe / placard : tablettes, tringle, porte',
        'Prises électriques et interrupteurs',
        'Chauffage : état de l\'appareil',
        'Porte : état, poignée, fermeture',
      ]),
      section('edl-chambre2', 'Chambre 2', [
        'Murs, plafond, plancher : état général',
        'Fenêtres et stores',
        'Garde-robe / placard',
        'Prises, interrupteurs, chauffage',
      ]),
      section('edl-chambre3', 'Chambre 3 (si applicable)', [
        'Murs, plafond, plancher : état général',
        'Fenêtres et stores',
        'Garde-robe / placard',
        'Prises, interrupteurs, chauffage',
      ]),
      section('edl-buanderie', 'Buanderie / rangement', [
        'Laveuse et sécheuse (si incluses) : état',
        'Raccordements eau chaude/froide et drainage',
        'Évent de sécheuse : état et raccordement',
        'Plancher et murs : état',
        'Éclairage et prises',
      ]),
      section('edl-sous-sol', 'Sous-sol (si applicable)', [
        'Murs et plancher : fissures, taches d\'eau',
        'Fenêtres de sous-sol : état et fonctionnement',
        'Traces d\'humidité ou d\'infiltration',
        'Chauffe-eau : état visible',
        'Panneau électrique : état visible',
        'Pompe de puisard (si applicable)',
      ]),
      section('edl-exterieur', 'Extérieur et parties communes', [
        'Balcon / terrasse : état du plancher, garde-corps',
        'Porte-patio ou porte arrière : état, serrure',
        'Escalier extérieur : état, mains courantes',
        'Stationnement : numéro, état',
        'Rangement extérieur / cabanon (si applicable)',
        'Boîte aux lettres et sonnette',
      ]),
      section('edl-conclusion', 'Conclusion et signatures', [
        'Résumé des anomalies constatées',
        'Photos jointes au dossier',
        'Signature du locataire sortant (si sortie)',
        'Signature du locataire entrant (si entrée)',
        'Signature du propriétaire / représentant',
      ]),
    ],
  },
  batiment: {
    sections: [
      section('bat-terrain', 'Terrain et environnement', [
        'Pente du terrain : drainage loin des fondations',
        'Trottoirs, allées et aires pavées : état',
        'Végétation : arbres proches du bâtiment, racines',
        'Murs de soutènement : état, inclinaison',
        'Clôtures et portails : état et sécurité',
        'Éclairage extérieur et signalisation d\'adresse',
        'Stationnement : drainage et état de surface',
      ]),
      section('bat-fondations', 'Fondations', [
        'Type de fondation (béton coulé, blocs, pierre)',
        'Fissures visibles : emplacement, largeur, orientation',
        'Signes d\'infiltration ou d\'efflorescence',
        'Imperméabilisation visible ou absence',
        'Drain de fondation : regard visible ou signes de déficience',
        'Vide sanitaire : accès, humidité, ventilation',
      ]),
      section('bat-structure', 'Structure et charpente', [
        'Murs porteurs : déformations, fissures significatives',
        'Poutre principale : état, portée, supports',
        'Colonnes de soutien : aplomb, corrosion, base',
        'Planchers : affaissement, rebondissement, craquement',
        'Charpente de toit visible : état des fermes ou chevrons',
        'Linteaux au-dessus des ouvertures : fissures',
      ]),
      section('bat-exterieur', 'Revêtement extérieur', [
        'Parement (brique, vinyle, bois, fibrociment) : état',
        'Solins : fenêtres, murs, cheminée',
        'Calfeutrage : joints fenêtres, portes, raccords',
        'Avant-toits, fascias, soffites : état',
        'Portes extérieures : état, étanchéité, seuil',
        'Garage : porte, mécanisme, coupe-feu',
        'Fenêtres extérieures : cadres, scellants, état',
      ]),
      section('bat-toiture', 'Toiture', [
        'Type de couverture (bardeaux, membrane, tôle)',
        'État du revêtement : âge estimé, usure',
        'Solins et scellants aux jonctions',
        'Gouttières et descentes pluviales',
        'Cheminée(s) : chapeau, maçonnerie, solin',
        'Évents de plomberie et ventilation',
        'Lucarnes et puits de lumière',
        'Méthode d\'observation documentée',
      ]),
      section('bat-plomberie', 'Plomberie', [
        'Entrée d\'eau principale et robinet d\'arrêt',
        'Type de tuyauterie (cuivre, PVC, PEX, galvanisé)',
        'Pression et débit aux robinets',
        'Chauffe-eau : type, âge, capacité, soupape T&P',
        'Toilettes : fonctionnement, étanchéité à la base',
        'Éviers, lavabos, bains : drainage, fuites',
        'Pompe de puisard : état, fonctionnement',
        'Clapet anti-retour (si visible)',
        'Ventilation plomberie (évents)',
        'Robinets extérieurs et brise-vide',
      ]),
      section('bat-electrique', 'Électricité', [
        'Entrée de service : aérien ou souterrain, mât',
        'Panneau principal : capacité, état, étiquetage',
        'Panneaux secondaires (si applicable)',
        'Mise à la terre : borne visible',
        'Câblage : type (Romex, BX, Knob & Tube)',
        'Prises DDFT/GFCI : SDB, cuisine, extérieur',
        'Prises AFCI (chambres si applicable)',
        'Interrupteurs et luminaires : échantillon',
        'Boîtes de jonction : couvertes et accessibles',
        'Fils d\'aluminium (si présents) : connexions',
      ]),
      section('bat-chauffage', 'Chauffage et climatisation', [
        'Système principal : type, énergie, âge estimé',
        'Fonctionnement par commandes normales',
        'Distribution : conduits, plinthes, radiateurs',
        'Thermostat : type et fonctionnement',
        'Climatiseur central : unité extérieure, drain',
        'Thermopompe (si applicable) : état',
        'Réservoir de combustible : état, supports',
        'Cheminée : conduit de fumée, dégagement',
        'Foyer / poêle à bois : plaque, dégagement',
      ]),
      section('bat-ventilation', 'Ventilation et isolation', [
        'Échangeur d\'air / VRC : état, fonctionnement',
        'Ventilateurs de salle de bain : fonctionnement',
        'Hotte de cuisine : évacuation',
        'Évent de sécheuse : raccordement, longueur',
        'Isolation combles : type, épaisseur estimée',
        'Pare-vapeur visible (si observable)',
        'Ventilation des combles : soffites, évents de toit',
        'Ventilation vide sanitaire (si applicable)',
      ]),
      section('bat-interieur', 'Intérieur', [
        'Murs, plafonds et planchers : état par pièce',
        'Portes intérieures : état, fonctionnement',
        'Escaliers intérieurs : marches, contremarches',
        'Garde-corps et mains courantes',
        'Fenêtres : état, mécanismes, condensation',
        'Armoires et comptoirs : cuisine, SDB',
        'Traces d\'infiltration, moisissure, condensation',
      ]),
      section('bat-securite', 'Sécurité des occupants', [
        'Détecteurs de fumée : présence, emplacement',
        'Détecteurs de CO : si combustion ou garage',
        'Garde-corps : hauteur, espacement, solidité',
        'Issues de secours : nombre, dégagement',
        'Éclairage de secours (si applicable)',
        'Séparation coupe-feu garage-habitation',
        'Fenêtre de sortie au sous-sol (chambre)',
      ]),
      batimentGrenierSection(),
    ],
  },
  cnesst: {
    sections: [
      section('sst-admin', 'Administration et documentation SST', [
        'Programme de prévention disponible et à jour',
        'Registre des accidents et incidents tenu',
        'Comité SST ou délégué désigné et identifié',
        'Plan d\'urgence affiché avec numéros (911, CSST, poison)',
        'Formation SIMDUT / matières dangereuses à jour',
        'Registre de formation des travailleurs',
        'Affichage des droits et obligations (LSST)',
        'Procédure de cadenassage documentée',
      ]),
      section('sst-chantier', 'Organisation du chantier', [
        'Périmètre de sécurité balisé et signalé',
        'Accès contrôlé : barrières, gardien, registre',
        'Séparation piétons / véhicules / équipements lourds',
        'Ordre, propreté et rangement des matériaux',
        'Éclairage adéquat des zones de travail',
        'Signalisation routière si voie publique',
        'Toilettes et eau potable accessibles',
        'Trousse de premiers soins complète et accessible',
      ]),
      section('sst-epi', 'Équipements de protection individuelle', [
        'Casque de sécurité : état et port obligatoire',
        'Lunettes ou visière de protection',
        'Gants adaptés au type de tâche',
        'Chaussures de sécurité à embout d\'acier',
        'Protection auditive si bruit > 85 dB',
        'Protection respiratoire si poussières / solvants',
        'Vêtements haute visibilité',
        'Harnais de sécurité si travail en hauteur > 3 m',
      ]),
      section('sst-hauteur', 'Travail en hauteur', [
        'Échafaudage monté par personne compétente',
        'Garde-corps et plinthes sur toutes plateformes',
        'Plancher complet et sécurisé',
        'Échelles : angle 4:1, dépasse de 1 m, pieds calés',
        'Lignes de vie et ancrages conformes',
        'Filets de sécurité (si applicable)',
        'Ouvertures dans plancher protégées',
        'Toit plat : protection périmétrique',
      ]),
      section('sst-electrique', 'Électricité et cadenassage', [
        'Câbles temporaires protégés et signalés',
        'Panneaux temporaires accessibles et dégagés',
        'Disjoncteurs et GFCI fonctionnels',
        'Outils à double isolation ou avec GFCI',
        'Procédure de cadenassage appliquée',
        'Cadenas personnels et étiquettes',
        'Distances de sécurité lignes électriques',
      ]),
      section('sst-excavation', 'Excavation et tranchées', [
        'Étançonnement ou talutage conforme',
        'Détection des services souterrains (Info-Excavation)',
        'Accès et sortie de la tranchée (échelle / rampe)',
        'Matériaux entreposés à 1.2 m du bord',
        'Surveillance de l\'atmosphère (si applicable)',
        'Pompage de l\'eau si accumulation',
      ]),
      section('sst-materiaux', 'Manutention et entreposage', [
        'Empilage stable et sécuritaire',
        'Allées dégagées pour circulation',
        'Utilisation correcte des aides mécaniques',
        'Matières dangereuses entreposées selon SIMDUT',
        'Bonbonnes de gaz arrimées et capuchonnées',
        'Conteneurs de déchets identifiés',
      ]),
    ],
  },
  mapaq: {
    sections: [
      section('map-general', 'Informations de l\'établissement', [
        'Permis MAPAQ valide et affiché',
        'Responsable hygiène désigné',
        'Plan de nettoyage et désinfection documenté',
        'Programme de lutte antiparasitaire actif',
        'Registre des températures tenu quotidiennement',
        'Formation en hygiène et salubrité du personnel',
      ]),
      section('map-personnel', 'Hygiène du personnel', [
        'Lavabo pour lavage des mains : savon, eau chaude, essuie-mains',
        'Lavage des mains pratiqué avant manipulation',
        'Tenue propre et adaptée (tablier, filet, gants)',
        'Cheveux retenus et couverts',
        'Bijoux limités selon politique',
        'Absence de symptômes infectieux',
        'Couvre-plaies étanches et colorés sur blessures',
        'Interdiction de manger dans les zones de préparation',
      ]),
      section('map-reception', 'Réception et entreposage', [
        'Vérification de la température à la réception',
        'Vérification des dates de péremption',
        'Intégrité des emballages vérifiée',
        'Entreposage au sol interdit (tablettes surélevées)',
        'Rotation des stocks (FIFO — Premier entré, premier sorti)',
        'Séparation des produits crus et prêts-à-manger',
        'Produits chimiques entreposés séparément',
        'Identification et datation des produits ouverts',
      ]),
      section('map-froid', 'Chaîne du froid', [
        'Réfrigérateur ≤ 4 °C — thermomètre visible',
        'Congélateur ≤ -18 °C — thermomètre visible',
        'Chambre froide : température conforme et enregistrée',
        'Thermomètres étalonnés et documentés',
        'Maintien du froid lors du transport',
        'Décongélation au réfrigérateur ou eau froide courante',
        'Aliments chauds maintenus ≥ 60 °C',
        'Refroidissement rapide (60 °C à 4 °C en ≤ 6 h)',
      ]),
      section('map-preparation', 'Préparation des aliments', [
        'Surfaces de travail propres et désinfectées',
        'Planches à découper codées par couleur',
        'Ustensiles nettoyés entre les utilisations',
        'Prévention de la contamination croisée',
        'Cuisson à température interne sécuritaire',
        'Thermomètre à sonde utilisé et étalonné',
        'Manipulation minimale des aliments prêts-à-manger',
      ]),
      section('map-nettoyage', 'Nettoyage et salubrité', [
        'Plan de nettoyage affiché et suivi',
        'Produits de nettoyage homologués et identifiés',
        'Désinfection des surfaces de contact alimentaire',
        'Lavage de vaisselle : température et détergent',
        'Poubelles avec couvercle et vidées régulièrement',
        'Planchers, murs, plafonds propres et en bon état',
        'Ventilation adéquate et filtres propres',
        'Absence de moisissure ou accumulation de graisse',
      ]),
      section('map-parasites', 'Lutte antiparasitaire', [
        'Programme de lutte documenté',
        'Aucun signe de rongeurs, insectes ou oiseaux',
        'Portes et fenêtres munies de moustiquaires',
        'Ouvertures extérieures scellées',
        'Pièges installés et vérifiés régulièrement',
        'Registre des interventions de l\'exterminateur',
      ]),
      section('map-tracabilite', 'Traçabilité et rappel', [
        'Registre des fournisseurs et lots',
        'Étiquetage des allergènes conforme',
        'Procédure de rappel connue et documentée',
        'Coordonnées des fournisseurs accessibles',
        'Registre des plaintes clients',
      ]),
    ],
  },
  incendie: {
    sections: [
      section('inc-general', 'Informations générales', [
        'Type de bâtiment et usage principal',
        'Nombre d\'étages et superficie',
        'Nombre d\'occupants maximal',
        'Classification du bâtiment selon CNPI',
        'Date de construction et rénovations majeures',
        'Rapport d\'inspection précédent (si disponible)',
      ]),
      section('inc-issues', 'Issues et moyens d\'évacuation', [
        'Nombre d\'issues de secours conforme au code',
        'Portes de sortie déverrouillables sans clé',
        'Couloirs et escaliers dégagés d\'obstacles',
        'Largeur minimale des corridors respectée',
        'Éclairage de secours fonctionnel (test)',
        'Signalisation EXIT / SORTIE visible et éclairée',
        'Plans d\'évacuation affichés à chaque étage',
        'Exercice d\'évacuation réalisé (date)',
      ]),
      section('inc-detection', 'Détection et alarme', [
        'Système d\'alarme incendie : type et fabricant',
        'Panneau de contrôle : sans trouble actif',
        'Avertisseurs de fumée : emplacement et test',
        'Détecteurs de chaleur (si requis)',
        'Avertisseurs manuels accessibles et identifiés',
        'Test annuel du système par technicien certifié',
        'Rapport de vérification annuelle disponible',
        'Batteries de secours chargées',
      ]),
      section('inc-extincteurs', 'Extincteurs portatifs', [
        'Emplacement visible, signalisé et accessible',
        'Hauteur d\'installation conforme (max 1.5 m)',
        'Inspection mensuelle documentée',
        'Entretien annuel par technicien certifié',
        'Type adapté au risque (A, B, C, K)',
        'Charge et scellé intacts',
        'Distance de parcours maximale respectée',
        'Étiquette d\'inspection à jour',
      ]),
      section('inc-sprinklers', 'Gicleurs automatiques (si applicable)', [
        'Têtes de gicleurs non obstruées (min 46 cm)',
        'Vanne principale ouverte et cadenassée',
        'Pression d\'eau adéquate',
        'Test de débit annuel documenté',
        'Gicleurs de remplacement disponibles',
        'Chauffage adéquat pour éviter le gel',
      ]),
      section('inc-compartimentage', 'Compartimentage et séparations', [
        'Portes coupe-feu à fermeture automatique',
        'Joints et quincaillerie coupe-feu intacts',
        'Traversées de conduits et câbles obturées',
        'Séparation garage / habitation conforme',
        'Cage d\'escalier : portes, murs intégrité',
        'Cloisons coupe-feu entre logements',
        'Vide de construction non contaminé',
      ]),
      section('inc-equipements', 'Équipements spéciaux', [
        'Génératrice de secours : état et carburant',
        'Ascenseurs : rappel pompiers fonctionnel',
        'Colonnes sèches / montantes (si applicable)',
        'Raccord pompier accessible',
        'Chambre électrique : accès et dégagement',
        'Salle des machines : ventilation',
        'Éclairage de secours dans escaliers',
      ]),
      section('inc-risques', 'Risques particuliers', [
        'Entreposage de matières dangereuses',
        'Bonbonnes de propane / gaz : entreposage',
        'Accumulation de matériaux combustibles',
        'Installations de cuisson commerciale',
        'Système d\'extinction de cuisine (type K)',
        'Fumoir ou zone fumeur : conformité',
      ]),
    ],
  },
  'aibq-preachat': { sections: AIBQ_SECTIONS },
  'bnq-3009': { sections: BNQ_SECTIONS },
  custom: {
    sections: [
      section('section-1', 'Section 1', [
        'Point de contrôle 1',
        'Point de contrôle 2',
        'Point de contrôle 3',
      ]),
    ],
  },
};

export function cloneTemplate(templateId) {
  const raw = TEMPLATES[templateId] ?? TEMPLATES.custom;
  return JSON.parse(JSON.stringify(raw));
}

export function createEmptyInspection(templateId) {
  const meta = TEMPLATE_META[templateId] ?? TEMPLATE_META.custom;
  const cloned = cloneTemplate(templateId);
  return {
    id: crypto.randomUUID(),
    templateId,
    templateLabel: meta.label,
    norme: meta.norme,
    status: 'brouillon',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    completedAt: null,
    site: {
      client: '',
      proprietaire: '',
      courtier: '',
      courrielClient: '',
      telephoneClient: '',
      adresse: '',
      ville: '',
      codePostal: '',
      typeBatiment: '',
      numeroDossier: '',
      categorieBnq: '',
      mandat: '',
    },
    visit: defaultVisit(),
    inspector: {
      nom: INSPECTOR_NAME,
      permis: '',
      entreprise: '',
      courriel: '',
      telephone: '',
      membreAibq: '',
      certificatRbq: '',
    },
    observations: '',
    thankYouNote: '',
    receipt: null,
    coverPhotoDataUrl: null,
    coverPhotoCaption: '',
    limitations: '',
    expertReferrals: [],
    signatureDataUrl: null,
    sections: cloned.sections,
  };
}
